# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/design/main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(910, 597)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.painter = Drawer(Form)
        self.painter.setGeometry(QtCore.QRect(30, 30, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.painter.sizePolicy().hasHeightForWidth())
        self.painter.setSizePolicy(sizePolicy)
        self.painter.setMinimumSize(QtCore.QSize(500, 500))
        self.painter.setMaximumSize(QtCore.QSize(500, 500))
        self.painter.setAutoFillBackground(False)
        self.painter.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border : 1px solid black;")
        self.painter.setObjectName("painter")
        self.loadImageButton = QtWidgets.QPushButton(Form)
        self.loadImageButton.setGeometry(QtCore.QRect(140, 550, 101, 31))
        self.loadImageButton.setObjectName("loadImageButton")
        self.ImageActionsGroupBox = QtWidgets.QGroupBox(Form)
        self.ImageActionsGroupBox.setGeometry(QtCore.QRect(540, 350, 181, 121))
        self.ImageActionsGroupBox.setObjectName("ImageActionsGroupBox")
        self.addImageButton = QtWidgets.QPushButton(self.ImageActionsGroupBox)
        self.addImageButton.setGeometry(QtCore.QRect(10, 70, 151, 31))
        self.addImageButton.setObjectName("addImageButton")
        self.trainButton = QtWidgets.QPushButton(self.ImageActionsGroupBox)
        self.trainButton.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.trainButton.setObjectName("trainButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(540, 30, 361, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.nnSettingTab = QtWidgets.QWidget()
        self.nnSettingTab.setObjectName("nnSettingTab")
        self.inputLabel = QtWidgets.QLabel(self.nnSettingTab)
        self.inputLabel.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.inputLabel.setObjectName("inputLabel")
        self.inputValueLabel = QtWidgets.QLabel(self.nnSettingTab)
        self.inputValueLabel.setGeometry(QtCore.QRect(80, 20, 47, 13))
        self.inputValueLabel.setText("")
        self.inputValueLabel.setObjectName("inputValueLabel")
        self.dropWeightsButton = QtWidgets.QPushButton(self.nnSettingTab)
        self.dropWeightsButton.setGeometry(QtCore.QRect(20, 40, 121, 31))
        self.dropWeightsButton.setObjectName("dropWeightsButton")
        self.loadModelButton = QtWidgets.QPushButton(self.nnSettingTab)
        self.loadModelButton.setGeometry(QtCore.QRect(20, 80, 121, 31))
        self.loadModelButton.setObjectName("loadModelButton")
        self.trainModelButton = QtWidgets.QPushButton(self.nnSettingTab)
        self.trainModelButton.setGeometry(QtCore.QRect(10, 230, 131, 31))
        self.trainModelButton.setObjectName("trainModelButton")
        self.saveModelButton = QtWidgets.QPushButton(self.nnSettingTab)
        self.saveModelButton.setGeometry(QtCore.QRect(20, 120, 121, 31))
        self.saveModelButton.setObjectName("saveModelButton")
        self.learningRateLabel = QtWidgets.QLabel(self.nnSettingTab)
        self.learningRateLabel.setGeometry(QtCore.QRect(160, 50, 121, 20))
        self.learningRateLabel.setObjectName("learningRateLabel")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.nnSettingTab)
        self.doubleSpinBox.setGeometry(QtCore.QRect(270, 50, 62, 22))
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 0.2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label = QtWidgets.QLabel(self.nnSettingTab)
        self.label.setGeometry(QtCore.QRect(160, 80, 101, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.nnSettingTab)
        self.spinBox.setGeometry(QtCore.QRect(270, 80, 42, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName("spinBox")
        self.tabWidget.addTab(self.nnSettingTab, "")
        self.datasetSettingsTab = QtWidgets.QWidget()
        self.datasetSettingsTab.setObjectName("datasetSettingsTab")
        self.imageNumberLabel = QtWidgets.QLabel(self.datasetSettingsTab)
        self.imageNumberLabel.setGeometry(QtCore.QRect(200, 10, 81, 16))
        self.imageNumberLabel.setObjectName("imageNumberLabel")
        self.imageNumberValueLabel = QtWidgets.QLabel(self.datasetSettingsTab)
        self.imageNumberValueLabel.setGeometry(QtCore.QRect(280, 10, 31, 16))
        self.imageNumberValueLabel.setObjectName("imageNumberValueLabel")
        self.nextImageButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.nextImageButton.setGeometry(QtCore.QRect(310, 10, 31, 31))
        self.nextImageButton.setObjectName("nextImageButton")
        self.previousImageButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.previousImageButton.setGeometry(QtCore.QRect(160, 10, 31, 31))
        self.previousImageButton.setObjectName("previousImageButton")
        self.removeImageButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.removeImageButton.setGeometry(QtCore.QRect(260, 240, 81, 31))
        self.removeImageButton.setObjectName("removeImageButton")
        self.clearDatasetButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.clearDatasetButton.setGeometry(QtCore.QRect(10, 50, 121, 31))
        self.clearDatasetButton.setObjectName("clearDatasetButton")
        self.loadDatasetButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.loadDatasetButton.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.loadDatasetButton.setObjectName("loadDatasetButton")
        self.classGroupBox = QtWidgets.QGroupBox(self.datasetSettingsTab)
        self.classGroupBox.setGeometry(QtCore.QRect(10, 140, 121, 91))
        self.classGroupBox.setObjectName("classGroupBox")
        self.class0Label = QtWidgets.QLabel(self.classGroupBox)
        self.class0Label.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.class0Label.setObjectName("class0Label")
        self.class1Label = QtWidgets.QLabel(self.classGroupBox)
        self.class1Label.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.class1Label.setObjectName("class1Label")
        self.class0ValueLabel = QtWidgets.QLabel(self.classGroupBox)
        self.class0ValueLabel.setGeometry(QtCore.QRect(60, 30, 47, 13))
        self.class0ValueLabel.setTextFormat(QtCore.Qt.PlainText)
        self.class0ValueLabel.setWordWrap(True)
        self.class0ValueLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.class0ValueLabel.setObjectName("class0ValueLabel")
        self.class1ValueLabel = QtWidgets.QLabel(self.classGroupBox)
        self.class1ValueLabel.setGeometry(QtCore.QRect(60, 60, 47, 13))
        self.class1ValueLabel.setTextFormat(QtCore.Qt.PlainText)
        self.class1ValueLabel.setWordWrap(True)
        self.class1ValueLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.class1ValueLabel.setObjectName("class1ValueLabel")
        self.saveDatasetButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.saveDatasetButton.setGeometry(QtCore.QRect(10, 240, 121, 31))
        self.saveDatasetButton.setObjectName("saveDatasetButton")
        self.editButton = QtWidgets.QPushButton(self.datasetSettingsTab)
        self.editButton.setGeometry(QtCore.QRect(160, 240, 91, 31))
        self.editButton.setObjectName("editButton")
        self.divider = QtWidgets.QFrame(self.datasetSettingsTab)
        self.divider.setGeometry(QtCore.QRect(130, 10, 20, 261))
        self.divider.setFrameShape(QtWidgets.QFrame.VLine)
        self.divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divider.setObjectName("divider")
        self.previewBox = PreviewBox(self.datasetSettingsTab)
        self.previewBox.setGeometry(QtCore.QRect(160, 50, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewBox.sizePolicy().hasHeightForWidth())
        self.previewBox.setSizePolicy(sizePolicy)
        self.previewBox.setMinimumSize(QtCore.QSize(180, 180))
        self.previewBox.setMaximumSize(QtCore.QSize(180, 180))
        self.previewBox.setAutoFillBackground(True)
        self.previewBox.setStyleSheet("")
        self.previewBox.setFrameShape(QtWidgets.QFrame.Box)
        self.previewBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.previewBox.setObjectName("previewBox")
        self.previewClassLabel = QtWidgets.QLabel(self.datasetSettingsTab)
        self.previewClassLabel.setGeometry(QtCore.QRect(220, 30, 47, 13))
        self.previewClassLabel.setText("")
        self.previewClassLabel.setObjectName("previewClassLabel")
        self.tabWidget.addTab(self.datasetSettingsTab, "")
        self.checkImageButton = QtWidgets.QPushButton(Form)
        self.checkImageButton.setGeometry(QtCore.QRect(550, 500, 151, 31))
        self.checkImageButton.setObjectName("checkImageButton")
        self.PenSettingsGroupBox = QtWidgets.QGroupBox(Form)
        self.PenSettingsGroupBox.setGeometry(QtCore.QRect(250, 540, 281, 51))
        self.PenSettingsGroupBox.setObjectName("PenSettingsGroupBox")
        self.penTypeBox = QtWidgets.QComboBox(self.PenSettingsGroupBox)
        self.penTypeBox.setGeometry(QtCore.QRect(10, 20, 100, 21))
        self.penTypeBox.setObjectName("penTypeBox")
        self.penColorBox = QtWidgets.QComboBox(self.PenSettingsGroupBox)
        self.penColorBox.setGeometry(QtCore.QRect(120, 20, 101, 21))
        self.penColorBox.setCurrentText("")
        self.penColorBox.setObjectName("penColorBox")
        self.spinSizeBox = QtWidgets.QSpinBox(self.PenSettingsGroupBox)
        self.spinSizeBox.setGeometry(QtCore.QRect(230, 20, 42, 22))
        self.spinSizeBox.setMinimum(1)
        self.spinSizeBox.setMaximum(15)
        self.spinSizeBox.setProperty("value", 2)
        self.spinSizeBox.setObjectName("spinSizeBox")
        self.clearCanvasButton = QtWidgets.QPushButton(Form)
        self.clearCanvasButton.setGeometry(QtCore.QRect(30, 550, 101, 31))
        self.clearCanvasButton.setObjectName("clearCanvasButton")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loadImageButton.setText(_translate("Form", "Загрузить..."))
        self.ImageActionsGroupBox.setTitle(_translate("Form", "Действия с изображением"))
        self.addImageButton.setText(_translate("Form", "Добавить в набор"))
        self.trainButton.setText(_translate("Form", "Обучить на изображении"))
        self.inputLabel.setText(_translate("Form", "Входов:"))
        self.dropWeightsButton.setText(_translate("Form", "Сбросить веса"))
        self.loadModelButton.setText(_translate("Form", "Загрузить модель..."))
        self.trainModelButton.setText(_translate("Form", "Обучить модель"))
        self.saveModelButton.setText(_translate("Form", "Сохранить модель"))
        self.learningRateLabel.setText(_translate("Form", "Скорость обучения:"))
        self.label.setText(_translate("Form", "Эпохи:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nnSettingTab), _translate("Form", "Модель"))
        self.imageNumberLabel.setText(_translate("Form", "Изображение -"))
        self.imageNumberValueLabel.setText(_translate("Form", "1"))
        self.nextImageButton.setText(_translate("Form", ">>"))
        self.previousImageButton.setText(_translate("Form", "<<"))
        self.removeImageButton.setText(_translate("Form", "Удалить"))
        self.clearDatasetButton.setText(_translate("Form", "Очистить"))
        self.loadDatasetButton.setText(_translate("Form", "Загрузить..."))
        self.classGroupBox.setTitle(_translate("Form", "Классы"))
        self.class0Label.setText(_translate("Form", "Класс 0:"))
        self.class1Label.setText(_translate("Form", "Класс 1:"))
        self.class0ValueLabel.setText(_translate("Form", "0"))
        self.class1ValueLabel.setText(_translate("Form", "1"))
        self.saveDatasetButton.setText(_translate("Form", "Сохранить набор"))
        self.editButton.setText(_translate("Form", "на полотно"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.datasetSettingsTab), _translate("Form", "Набор данных"))
        self.checkImageButton.setText(_translate("Form", "Распознать"))
        self.PenSettingsGroupBox.setTitle(_translate("Form", "Настройки кисти"))
        self.clearCanvasButton.setText(_translate("Form", "Очистить"))

from ui.components.drawer import Drawer
from ui.components.preview_box import PreviewBox
